name: Java CI with Maven

on:
  push:
    branches: [ main, master, krishna ]
  pull_request:
    branches: [ main, master, krishna ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Or adopt, zulu, etc.
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install
